swagger: '2.0'
info:
  version: '1.0'
  title: githubV2
  contact: {}
host: https://api.github.com
basePath: /api
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /check:
    get:
      summary: server check
      tags:
      - Misc
      operationId: servercheck
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /repo:
    get:
      summary: get repo with filters
      tags:
      - Misc
      operationId: getrepowithfilters
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: keyword
        in: query
        required: true
        type: string
        description: ''
      - name: created
        in: query
        required: true
        type: string
        description: ''
      - name: stars
        in: query
        required: true
        type: string
        description: ''
      - name: forks
        in: query
        required: true
        type: string
        description: ''
      - name: language
        in: query
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /graphql:
    post:
      summary: graphql search
      tags:
      - Misc
      operationId: graphqlsearch
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
tags:
- name: Misc
  description: ''
